name: registerpage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/App icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/screw driver.jpg
    - assets/images/logo2.jpeg
    - assets/images/buy.jpeg
    - assets/images/open.jpeg
